import 'dart:async';
import 'dart:io';
import '../../domain/word_to_pdf_engine.dart';
import '../../../../../core/storage/storage_service.dart';

class ComWordToPdfEngine extends WordToPdfEngine {
  final StorageService storageService;

  ComWordToPdfEngine(this.storageService);

  @override
  String get engineId => 'com.microsoft.word';

  @override
  Future<bool> isAvailable() async {
    if (!Platform.isWindows) return false;
    
    try {
      final result = await Process.run('powershell', [
        '-Command', 
        'try { \$app = New-Object -ComObject Word.Application; [System.Runtime.Interopservices.Marshal]::ReleaseComObject(\$app) | Out-Null; exit 0 } catch { exit 1 }'
      ]);
      return result.exitCode == 0;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<bool> healthCheck() async => await isAvailable();

  @override
  Future<String> engineVersion() async => '1.0.0-windows-com';

  @override
  List<String> get supportedCapabilities => ['High Fidelity', 'Native Office rendering', 'Fast'];

  @override
  Future<void> convert(File input, File output, {StreamController<double>? progress}) async {
    if (!Platform.isWindows) throw Exception('COM automation requires Windows');
    
    progress?.add(0.1);
    
    // wdFormatPDF = 17
    final psScript = '''
\$ErrorActionPreference = "Stop"
try {
    \$word = New-Object -ComObject Word.Application
    \$word.Visible = \$false
    \$word.DisplayAlerts = "wdAlertsNone"
    
    \$doc = \$word.Documents.Open("${input.absolute.path}", \$false, \$true)
    \$doc.SaveAs([ref] "${output.absolute.path}", [ref] 17)
    \$doc.Close([ref] 0)
    
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject(\$doc) | Out-Null
} finally {
    if (\$word) {
        \$word.Quit([ref] 0)
        [System.Runtime.Interopservices.Marshal]::ReleaseComObject(\$word) | Out-Null
    }
    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
}
''';

    progress?.add(0.4);

    final psFilePath = await storageService.getTempPath('word_convert_${DateTime.now().millisecondsSinceEpoch}.ps1');
    final psFile = File(psFilePath);
    await psFile.writeAsString(psScript);

    final result = await Process.run('powershell', [
      '-NoProfile', 
      '-NonInteractive', 
      '-ExecutionPolicy', 
      'Bypass', 
      '-File', 
      psFile.absolute.path
    ]);
    
    if (await psFile.exists()) {
      await psFile.delete();
    }
    
    progress?.add(0.9);
    
    if (result.exitCode != 0) {
      throw Exception('Word COM Conversion failed: ${result.stderr}');
    }
    
    if (!await output.exists()) {
      throw Exception('Output file was not generated by Word');
    }
    
    progress?.add(1.0);
  }
}
