import 'dart:async';
import 'dart:io';
import '../../domain/pptx_to_pdf_engine.dart';
import '../../../../../core/storage/storage_service.dart';

class ComPptxToPdfEngine extends PptxToPdfEngine {
  final StorageService storageService;

  ComPptxToPdfEngine(this.storageService);

  @override
  String get engineId => 'com.microsoft.powerpoint';

  @override
  Future<bool> isAvailable() async {
    if (!Platform.isWindows) return false;
    
    try {
      final result = await Process.run('powershell', [
        '-Command', 
        'try { \$app = New-Object -ComObject Powerpoint.Application; [System.Runtime.Interopservices.Marshal]::ReleaseComObject(\$app) | Out-Null; exit 0 } catch { exit 1 }'
      ]);
      return result.exitCode == 0;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<bool> healthCheck() async => await isAvailable();

  @override
  Future<String> engineVersion() async => '1.0.0-windows-com';

  @override
  List<String> get supportedCapabilities => ['High Fidelity', 'Native Office rendering', 'Fast'];

  @override
  Future<void> convert(File input, File output, {StreamController<double>? progress}) async {
    if (!Platform.isWindows) throw Exception('COM automation requires Windows');
    
    progress?.add(0.1);
    
    final psScript = '''
\$ErrorActionPreference = "Stop"
try {
    \$ppt = New-Object -ComObject PowerPoint.Application
    \$ppt.DisplayAlerts = "ppAlertsNone"
    
    \$presentation = \$ppt.Presentations.Open("${input.absolute.path}", \$true, \$false, \$false)
    \$presentation.SaveAs("${output.absolute.path}", 32)
    \$presentation.Close()
    
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject(\$presentation) | Out-Null
} finally {
    if (\$ppt) {
        \$ppt.Quit()
        [System.Runtime.Interopservices.Marshal]::ReleaseComObject(\$ppt) | Out-Null
    }
    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
}
''';

    progress?.add(0.4);

    final psFilePath = await storageService.getTempPath('ppt_convert_${DateTime.now().millisecondsSinceEpoch}.ps1');
    final psFile = File(psFilePath);
    await psFile.writeAsString(psScript);

    final result = await Process.run('powershell', [
      '-NoProfile', 
      '-NonInteractive', 
      '-ExecutionPolicy', 
      'Bypass', 
      '-File', 
      psFile.absolute.path
    ]);
    
    if (await psFile.exists()) {
      await psFile.delete();
    }
    
    progress?.add(0.9);
    
    if (result.exitCode != 0) {
      throw Exception('PowerPoint COM Conversion failed: ${result.stderr}');
    }
    
    if (!await output.exists()) {
      throw Exception('Output file was not generated by PowerPoint');
    }
    
    progress?.add(1.0);
  }
}
