import 'dart:async';
import 'dart:io';
import '../../domain/pptx_to_pdf_engine.dart';
import '../../../../../core/engine/manager/engine_manager.dart';
import '../../../../../core/engine/models/engine_info.dart';

class LibreOfficePptxToPdfEngine extends PptxToPdfEngine {
  final EngineManager manager;
  
  LibreOfficePptxToPdfEngine(this.manager);

  @override
  String get engineId => 'org.libreoffice.headless';

  @override
  Future<bool> isAvailable() async {
    final info = await manager.getEngineInfo(engineId);
    return info != null && info.status == EngineStatus.installed;
  }

  @override
  Future<bool> healthCheck() async => await isAvailable();

  @override
  Future<String> engineVersion() async => '1.0.0-libreoffice';

  @override
  List<String> get supportedCapabilities => ['Cross-platform', 'Fallback rendering'];

  @override
  Future<void> convert(File input, File output, {StreamController<double>? progress}) async {
    progress?.add(0.2);
    
    // The path to soffice would normally be provided by the EngineManager's binary path registry.
    // For MVP, we assume it's in the system PATH if marked as installed.
    final result = await Process.run('soffice', [
      '--headless',
      '--convert-to',
      'pdf',
      input.absolute.path,
      '--outdir',
      output.parent.absolute.path,
    ]);
    
    progress?.add(0.9);
    
    if (result.exitCode != 0) {
      throw Exception('LibreOffice Conversion failed: ${result.stderr}');
    }
    
    // LibreOffice saves the file with the original basename but .pdf extension.
    // We need to rename it to the requested output file name if it differs.
    final generatedName = input.uri.pathSegments.last.replaceAll(RegExp(r'\.pptx?$'), '.pdf');
    final generatedFile = File('${output.parent.absolute.path}/$generatedName');
    
    if (await generatedFile.exists()) {
      if (generatedFile.absolute.path != output.absolute.path) {
        await generatedFile.rename(output.absolute.path);
      }
    } else {
      throw Exception('Output file was not generated by LibreOffice');
    }
    
    progress?.add(1.0);
  }
}
